insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'オキナワオオコウモリ', 'Pteropus loochoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'ミヤココキクガシラコウモリ', 'Rhinolophus pumilus miyakonis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'オガサワラアブラコウモリ', 'Pipistrellus sturdeei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'エゾオオカミ', 'Canis lupus hattai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'ニホンオオカミ', 'Canis lupus hodophilax');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'ニホンカワウソ（本州以南亜種）', 'Lutra lutra nippon');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '哺乳類', 'ニホンカワウソ（北海道亜種）', 'Lutra lutra whiteleyi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'センカクモグラ', 'Mogera uchidai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'ダイトウオオコウモリ', 'Pteropus dasymallus daitoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'エラブオオコウモリ', 'Pteropus dasymallus dasymallus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'クロアカコウモリ', 'Myotis formosus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'ヤンバルホオヒゲコウモリ', 'Myotis yanbarensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'オキナワトゲネズミ', 'Tokudaia muenninki');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'セスジネズミ', 'Apodemus agrarius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'ツシマヤマネコ', 'Prionailurus bengalensis euptilurus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'イリオモテヤマネコ', 'Prionailurus bengalensis iriomotensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'ラッコ', 'Enhydra lutris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'ニホンアシカ', 'Zalophus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '哺乳類', 'ジュゴン', 'Dugong dugon');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'オリイジネズミ', 'Crocidura orii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'エチゴモグラ', 'Mogera etigo');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'オガサワラオオコウモリ', 'Pteropus pselaphon');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'オリイコキクガシラコウモリ', 'Rhinolophus cornutus orii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'オキナワコキクガシラコウモリ', 'Rhinolophus pumilus pumilus ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'コヤマコウモリ', 'Nyctalus furvus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'リュウキュウユビナガコウモリ', 'Miniopterus fuscus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'リュウキュウテングコウモリ', 'Murina ryukyuana');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'アマミトゲネズミ', 'Tokudaia osimensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'トクノシマトゲネズミ', 'Tokudaia tokunoshimensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'ケナガネズミ', 'Diplothrix legata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '哺乳類', 'アマミノクロウサギ', 'Pentalagus furnessi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'トウキョウトガリネズミ', 'Sorex minutissimus hawkeri　');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'ヤエヤマコキクガシラコウモリ', 'Rhinolophus perditus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'クビワコウモリ', 'Eptesicus japonensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'ヤマコウモリ', 'Nyctalus aviator');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'モリアブラコウモリ', 'Pipistrellus endoi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'ウスリホオヒゲコウモリ', 'Myotis gracilis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'ホンドノレンコウモリ', 'Myotis nattereri bombinus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'クロホオヒゲコウモリ', 'Myotis pruinosus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'オヒキコウモリ', 'Tadarida insignis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '哺乳類', 'ゼニガタアザラシ', 'Phoca vitulina');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'アズミトガリネズミ', 'Sorex hosonoi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'シコクトガリネズミ', 'Sorex shinto shikokensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'コジネズミ', 'Crocidura shantungensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'ワタセジネズミ', 'Crocidura watasei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'ミズラモグラ', 'Euroscaptor mizura');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'サドモグラ', 'Mogera tokudae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'ミヤマムクゲネズミ', 'Myodes rex montanus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'リシリムクゲネズミ', 'Myodes rex rex');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'エゾナキウサギ', 'Ochotona hyperborea yesoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'サドノウサギ', 'Lepus brachyurus lyoni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'チョウセンイタチ', 'Mustela sibirica coreana');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'ニホンイイズナ（本州亜種）', 'Mustela nivalis namiyei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'ホンドオコジョ', 'Mustela erminea nippon');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'エゾオコジョ', 'Mustela erminea orientalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'ツシマテン', 'Martes melampus tsuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'エゾクロテン', 'Martes zibellina brachyura');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '哺乳類', 'トド', 'Eumetopias jubatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '哺乳類', 'オオアブラコウモリ', 'Hypsugo alaschanicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '哺乳類', 'ヒメヒナコウモリ', 'Vespertilio murinus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '哺乳類', 'クチバテングコウモリ', 'Murina tenebrosa');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '哺乳類', 'スミイロオヒキコウモリ', 'Tadarida latouchei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '哺乳類', 'エゾシマリス', 'Tamias sibiricus lineatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '九州地方のカワネズミ', 'Chimarrogale platycephala');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '与那国島のカグラコウモリ', 'Hipposideros  turpis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '波照間島のカグラコウモリ', 'Hipposideros  turpis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '本州のチチブコウモリ', 'Barbastella leucomelas');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '四国のチチブコウモリ', 'Barbastella leucomelas');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '近畿地方以西のウサギコウモリ', 'Plecotus sacrimontis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '紀伊半島のシナノホオヒゲコウモリ', 'Myotis ikonnikovi hosonoi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '中国地方のシナノホオヒゲコウモリ', 'Myotis ikonnikovi hosonoi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '北奥羽・北上山系のホンドザル', 'Macaca fuscata fuscata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '金華山のホンドザル', 'Macaca fuscata fuscata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '中国地方のニホンリス', 'Sciurus lis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '九州地方のニホンリス', 'Sciurus lis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '天塩・増毛地方のエゾヒグマ', 'Ursus arctos yezoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '石狩西部のエゾヒグマ', 'Ursus arctos yezoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '下北半島のツキノワグマ', 'Ursus thibetanus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '紀伊半島のツキノワグマ', 'Ursus thibetanus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '東中国地域のツキノワグマ', 'Ursus thibetanus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '西中国地域のツキノワグマ', 'Ursus thibetanus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '四国山地のツキノワグマ', 'Ursus thibetanus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '馬毛島のニホンジカ', 'Cervus nippon');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '徳之島のリュウキュウイノシシ', 'Sus scrofa riukiuanus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '哺乳類', '九州地方のカモシカ', 'Capricornis crispus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'カンムリツクシガモ', 'Tadorna cristata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ダイトウノスリ', 'Buteo buteo oshiroi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'マミジロクイナ', 'Poliolimnas cinereus brevipes');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'リュウキュウカラスバト', 'Columba jouyi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'オガサワラカラスバト', 'Columba versicolor');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ミヤコショウビン', 'Halcyon miyakoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'キタタキ', 'Dryocopus javensis richardsi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ダイトウミソサザイ', 'Troglodytes troglodytes orii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'オガサワラガビチョウ', 'Cichlopasser terrestris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ダイトウウグイス', 'Cettia diphone restricta');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ダイトウヤマガラ', 'Parus varius orii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ムコジマメグロ', 'Apalopteron familiare familiare');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'オガサワラマシコ', 'Chaunoproctus ferreorostris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('野生絶滅（EW）', '鳥類', 'トキ', 'Nipponia nippon');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'オガサワラヒメミズナギドリ', 'Puffinus bryani');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'クロコシジロウミツバメ', 'Oceanodroma castro');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'チシマウガラス', 'Phalacrocorax urile');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'オオヨシゴイ', 'Ixobrychus eurhythmus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'コウノトリ', 'Ciconia boyciana');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'シジュウカラガン', 'Branta canadensis leucopareia');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ハクガン', 'Anser caerulescens caerulescens');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'カンムリワシ', 'Spilornis cheela perplexus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ヤンバルクイナ', 'Gallirallus okinawae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ヘラシギ', 'Eurynorhynchus pygmeus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'カラフトアオアシシギ', 'Tringa guttifer');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ウミガラス', 'Uria aalge inornata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ウミスズメ', 'Synthliboramphus antiquus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'エトピリカ', 'Lunda cirrhata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'アカガシラカラスバト', 'Columba janthina nitens');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ワシミミズク', 'Bubo bubo');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'シマフクロウ', 'Ketupa blakistoni blakistoni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'キンメフクロウ', 'Aegolius funereus magnus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ノグチゲラ', 'Sapheopipo noguchii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'ミユビゲラ', 'Picoides tridactylus inouyei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'チゴモズ', 'Lanius tigrinus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'シマアオジ', 'Emberiza aureola ornata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '鳥類', 'オガサワラカワラヒワ', 'Carduelis sinica kittlitzi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'コアホウドリ', 'Diomedea immutabilis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'セグロミズナギドリ', 'Puffinus lherminieri bannermani');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'アカオネッタイチョウ', 'Phaethon rubricauda rothschildi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'アカアシカツオドリ', 'Sula sula rubripes');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ヒメウ', 'Phalacrocorax pelagicus pelagicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'サンカノゴイ', 'Botaurus stellaris stellaris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'クロツラヘラサギ', 'Platalea minor');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'カリガネ', 'Anser erythropus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'リュウキュウツミ', 'Accipiter gularis iwasakii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'オガサワラノスリ', 'Buteo buteo toyoshimai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'クマタカ', 'Spizaetus nipalensis orientalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'イヌワシ', 'Aquila chrysaetos japonica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'チュウヒ', 'Circus spilonotus spilonotus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ライチョウ', 'Lagopus mutus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'オオクイナ', 'Rallina eurizonoides sepiaria');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'シマクイナ', 'Coturnicops noveboracensis exquisitus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'コシャクシギ', 'Numenius minutus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ヨナクニカラスバト', 'Columba janthina stejnegeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'シラコバト', 'Streptopelia decaocto decaocto');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'キンバト', 'Chalcophaps indica yamashinai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ブッポウソウ', 'Eurystomus orientalis calonyx');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ヤイロチョウ', 'Pitta brachyura nympha');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'アカモズ', 'Lanius cristatus superciliosus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'モスケミソサザイ', 'Troglodytes troglodytes mosukei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ホントウアカヒゲ', 'Erithacus komadori namiyei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'アカコッコ', 'Turdus celaenops');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'オオセッカ', 'Locustella pryeri pryeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ウチヤマセンニュウ', 'Locustella pleskei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ナミエヤマガラ', 'Parus varius namiyei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'オーストンヤマガラ', 'Parus varius owstoni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '鳥類', 'ハハジマメグロ', 'Apalopteron familiare hahasima');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'アホウドリ', 'Diomedea albatrus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ヒメクロウミツバメ', 'Oceanodroma monorhis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ミゾゴイ', 'Gorsachius goisagi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ズグロミゾゴイ', 'Gorsachius melanolophus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'コクガン', 'Branta bernicla orientalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ヒシクイ', 'Anser fabalis serrirostris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ツクシガモ', 'Tadorna tadorna');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'トモエガモ', 'Anas formosa');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'オジロワシ', 'Haliaeetus albicilla albicilla');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'オオワシ', 'Haliaeetus pelagicus pelagicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'サシバ', 'Butastur indicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ハヤブサ', 'Falco peregrinus japonensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ウズラ', 'Coturnix japonica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'タンチョウ', 'Grus japonensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ナベヅル', 'Grus monacha');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'マナヅル', 'Grus vipio');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'タマシギ', 'Rostratula benghalensis benghalensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'シロチドリ', 'Charadrius alexandrinus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ツルシギ', 'Tringa erythropus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'アカアシシギ', 'Tringa totanus ussuriensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'タカブシギ', 'Tringa glareola');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'オオソリハシシギ', 'Limosa lapponica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ホウロクシギ', 'Numenius madagascariensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'アマミヤマシギ', 'Scolopax mira');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'セイタカシギ', 'Himantopus himantopus himantopus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ツバメチドリ', 'Glareola maldivarum');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ズグロカモメ', 'Larus saundersi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'オオアジサシ', 'Thalasseus bergii cristatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ベニアジサシ', 'Sterna dougallii bangsi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'エリグロアジサシ', 'Sterna sumatrana');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'コアジサシ', 'Sterna albifrons sinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ケイマフリ', 'Cepphus carbo');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'カンムリウミスズメ', 'Synthliboramphus wumizusume');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'ダイトウコノハズク', 'Otus elegans interpositus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'リュウキュウオオコノハズク', 'Otus lempiji pryeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'クマゲラ', 'Dryocopus martius martius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'オーストンオオアカゲラ', 'Dendrocopos leucotos owstoni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'サンショウクイ', 'Pericrocotus divaricatus divaricatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'タネコマドリ', 'Erithacus akahige tanensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'アカヒゲ', 'Erithacus komadori komadori');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'オオトラツグミ', 'Zoothera dauma major');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'イイジマムシクイ', 'Phylloscopus ijimae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '鳥類', 'コジュリン', 'Emberiza yessoensis yessoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'オーストンウミツバメ', 'Oceanodroma tristrami');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'クロウミツバメ', 'Oceanodroma matsudairae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ヨシゴイ', 'Ixobrychus sinensis sinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'チュウサギ', 'Egretta intermedia intermedia');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'カラシラサギ', 'Egretta eulophotes');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'マガン', 'Anser albifrons frontalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'オオヒシクイ', 'Anser fabalis middendorffii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ミサゴ', 'Pandion haliaetus haliaetus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ハチクマ', 'Pernis apivorus orientalis　');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'オオタカ', 'Accipiter gentilis fujiyamae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ハイタカ', 'Accipiter nisus nisosimilis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'アカヤマドリ', 'Syrmaticus soemmerringii soemmerringii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'コシジロヤマドリ', 'Syrmaticus soemmerringii ijimae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ヒクイナ', 'Porzana fusca erythrothorax');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ハマシギ', 'Calidris alpina');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'オオジシギ', 'Gallinago hardwickii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'カラスバト', 'Columba janthina janthina');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ヨタカ', 'Caprimulgus indicus jotaka');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'マキノセンニュウ', 'Locustella lanceolata ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'オリイヤマガラ', 'Parus varius olivaceus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '鳥類', 'ノジコ', 'Emberiza sulphurata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'シロハラミズナギドリ', 'Pterodroma hypoleuca');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'ヘラサギ', 'Platalea leucorodia major');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'クロトキ', 'Threskiornis melanocephalus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'サカツラガン', 'Anser cygnoides');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'アカツクシガモ', 'Tadorna ferruginea');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'オシドリ', 'Aix galericulata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'アカハジロ', 'Aythya baeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'シマハヤブサ', 'Falco peregrinus furuitii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'エゾライチョウ', 'Tetrastes bonasia vicinitas');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'クロヅル', 'Grus grus lilfordi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'ケリ', 'Vanellus cinereus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'チシマシギ', 'Calidris ptilocnemis kurilensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'シベリアオオハシシギ', 'Limnodromus semipalmatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'マダラウミスズメ', 'Brachyramphus marmoratus perdix');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'ウスアカヒゲ', 'Erithacus komadori subrufus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'コトラツグミ', 'Zoothera dauma horsfieldi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '鳥類', 'ウグイスの1亜種', 'Cettia diphone ssp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '鳥類', '青森県のカンムリカイツブリ繁殖個体群', 'Podiceps cristatus cristatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '鳥類', '東北地方以北のシノリガモ繁殖個体群', 'Histrionicus histrionicus pacificus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX）', '鳥類', 'ハシブトゴイ', 'Nycticorax caledonicus crassirostris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '爬虫類', 'イヘヤトカゲモドキ', 'Goniurosaurus kuroiwae toyamai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '爬虫類', 'クメトカゲモドキ', 'Goniurosaurus kuroiwae yamashinae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '爬虫類', 'ミヤコカナヘビ', 'Takydromus toyamai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '爬虫類', 'キクザトサワヘビ', 'Opisthotropis kikuzatoi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'アカウミガメ', 'Caretta caretta');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'タイマイ', 'Eretmochelys imbricata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'オビトカゲモドキ', 'Goniurosaurus kuroiwae splendens');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'マダラトカゲモドキ', 'Goniurosaurus kuroiwae orientalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'アオスジトカゲ', 'Plestiodon elegans');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'シュウダ', 'Elaphe carinata carinata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'ヨナグニシュウダ', 'Elaphe carinata yonaguniensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'ミヤコヒバァ', 'Amphiesma concelarum');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '爬虫類', 'ミヤコヒメヘビ', 'Calamaria pfefferi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'アオウミガメ', 'Chelonia mydas mydas');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ヤエヤマセマルハコガメ', 'Cuora flavomarginata evelynae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'リュウキュウヤマガメ', 'Geoemyda japonica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'クロイワトカゲモドキ', 'Goniurosaurus kuroiwae kuroiwae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ミナミトリシマヤモリ', 'Perochirus ateles');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'タシロヤモリ', 'Hemidactylus bowringii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ヤクヤモリ', 'Gekko yakuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'オキナワキノボリトカゲ', 'Japalura polygonata polygonata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ヨナグニキノボリトカゲ', 'Japalura polygonata donan');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'オキナワトカゲ', 'Plestiodon marginatus marginatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'キシノウエトカゲ', 'Plestiodon kishinouyei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'バーバートカゲ', 'Plestiodon barbouri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ミヤコトカゲ', 'Emoia atrocostata atrocostata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'サキシマカナヘビ', 'Takydromus dorsalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'コモチカナヘビ', 'Zootoca vivipara');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ヤエヤマタカチホヘビ', 'Achalinus formosanus chigirai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'サキシマスジオ', 'Elaphe taeniura schmackeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ミヤラヒメヘビ', 'Calamaria pavimentata miyarai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'クメジマハイ', 'Sinomicrurus japonicus takarai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'イワサキワモンベニヘビ', 'Sinomicrurus macclellandi iwasakii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'エラブウミヘビ', 'Laticauda semifasciata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'ヒロオウミヘビ', 'Laticauda laticaudata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '爬虫類', 'イイジマウミヘビ', 'Emydocephalus ijimae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'ニホンイシガメ', 'Mauremys japonica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'オキナワヤモリ', 'Gekko sp. 1');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'タカラヤモリ', 'Gekko shibatai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'タワヤモリ', 'Gekko tawaensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'サキシマキノボリトカゲ', 'Japalura polygonata ishigakiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'オガサワラトカゲ', 'Cryptoblepharus nigropunctatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'イシガキトカゲ', 'Plestiodon stimpsonii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'オオシマトカゲ', 'Plestiodon marginatus oshimensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'アムールカナヘビ', 'Takydromus amurensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'サキシマアオヘビ', 'Cyclophiops herminae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'サキシマバイカダ', 'Lycodon ruhstrati multifasciatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'イワサキセダカヘビ', 'Pareas iwasakii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'アマミタカチホヘビ', 'Achalinus werneri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'アカマダラ', 'Dinodon rufozonatum rufozonatum');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'ハイ', 'Sinomicrurus japonicus boettgeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'ヒャン', 'Sinomicrurus japonicus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '爬虫類', 'トカラハブ', 'Protobothrops tokarensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '爬虫類', 'ニホンスッポン', 'Pelodiscus sinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '爬虫類', 'ツシマスベトカゲ', 'Scincella vandenburghi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '爬虫類', 'ダンジョヒバカリ', 'Amphiesma vibakari danjoense');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '爬虫類', '大東諸島のオガサワラヤモリ', 'Lepidodactylus lugubris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '爬虫類', '三宅島、八丈島、青ヶ島のオカダトカゲ', 'Plestiodon latiscutatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '爬虫類', '三島のヘリグロヒメトカゲ', 'Ateuchosaurus pellopleurus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '爬虫類', '沖永良部島、徳之島のアオカナヘビ', 'Takydromus smaragdinus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '爬虫類', '宮古諸島のサキシママダラ', 'Dinodon rufozonatum walli');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR）', '両生類', 'アベサンショウウオ', 'Hynobius abei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'アカイシサンショウウオ', 'Hynobius katoi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'ハクバサンショウウオ', 'Hynobius hidamontanus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'ホクリクサンショウウオ', 'Hynobius takedai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'ナゴヤダルマガエル', 'Rana porosa brevipoda');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'ナミエガエル', 'Limnonectes namiyei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'アマミイシカワガエル', 'Odorrana splendida');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'オキナワイシカワガエル', 'Odorrana ishikawae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'コガタハナサキガエル', 'Odorrana utsunomiyaorum');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'オットンガエル', 'Babina subaspera');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN）', '両生類', 'ホルストガエル', 'Babina holsti');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'オオイタサンショウウオ', 'Hynobius dunni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'オオダイガハラサンショウウオ', 'Hynobius boulengeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'オキサンショウウオ', 'Hynobius okiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'カスミサンショウウオ', 'Hynobius nebulosus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'トウキョウサンショウウオ', 'Hynobius tokyoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'ベッコウサンショウウオ', 'Hynobius stejnegeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'オオサンショウウオ', 'Andrias japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'イボイモリ', 'Echinotriton andersoni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'ヤエヤマハラブチガエル', 'Rana okinavana');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'アマミハナサキガエル', 'Odorrana amamiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU）', '両生類', 'ハナサキガエル', 'Odorrana narina');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'キタサンショウウオ', 'Salamandrella keyserlingii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'イシヅチサンショウウオ', 'Hynobius hirosei ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'クロサンショウウオ', 'Hynobius nigrescens');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'コガタブチサンショウウオ', 'Hynobius yatsui ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'ツシマサンショウウオ', 'Hynobius tsuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'トウホクサンショウウオ', 'Hynobius lichenatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'ヒダサンショウウオ', 'Hynobius kimurae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'ブチサンショウウオ', 'Hynobius naevius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'アカハライモリ', 'Cynops pyrrhogaster');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'シリケンイモリ', 'Cynops ensicauda');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'ミヤコヒキガエル', 'Bufo gargarizans miyakonis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'アマミアカガエル', 'Rana kobai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'オキタゴガエル', 'Rana tagoi okiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'ヤクシマタゴガエル', 'Rana tagoi yakushimensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'トウキョウダルマガエル', 'Rana porosa porosa');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'チョウセンヤマアカガエル', 'Rana dybowskii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'ツシマアカガエル', 'Rana tsushimensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'トノサマガエル', 'Rana nigromaculata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'リュウキュウアカガエル', 'Rana ulma');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT）', '両生類', 'オオハナサキガエル', 'Odorrana supranarina');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD）', '両生類', 'エゾサンショウウオ', 'Hynobius retardatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX)', '汽水・淡水魚類', 'チョウザメ', 'Acipenser medirostris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX)', '汽水・淡水魚類', 'スワモロコ', 'Gnathopogon elongatus suwae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅（EX)', '汽水・淡水魚類', 'ミナミトミヨ', 'Pungitius kaibarae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('野生絶滅（EW）', '汽水・淡水魚類', 'クニマス', 'Oncorhynchus kawamurae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'コゲウツボ', 'Uropterygius concolor');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ナミダカワウツボ', 'Echidna rhodochilus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'フナ属の１種（琉球列島）', 'Carassius sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ミヤコタナゴ', 'Tanakia tanago');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'イチモンジタナゴ', 'Acheilognathus cyanostigma');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'イタセンパラ', 'Acheilognathus longipinnis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ミナミアカヒレタビラ', 'Acheilognathus tabira jordani');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'セボシタビラ', 'Acheilognathus tabira nakamurae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ゼニタナゴ', 'Acheilognathus typus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ニッポンバラタナゴ', 'Rhodeus ocellatus kurumeus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'スイゲンゼニタナゴ', 'Rhodeus atremius suigensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ワタカ', 'Ischikauia steenackeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヒナモロコ', 'Aphyocypris chinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'シナイモツゴ', 'Pseudorasbora pumila pumila');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ウシモツゴ', 'Pseudorasbora pumila subsp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アブラヒガイ', 'Sarcocheilichthys biwaensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ホンモロコ', 'Gnathopogon caerulescens');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'サンヨウコガタスジシマドジョウ', 'Cobitis minamorii minamorii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ハカタスジシマドジョウ', 'Cobitis striata hakataensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'タンゴスジシマドジョウ', 'Cobitis sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アユモドキ', 'Parabotia curta');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'リュウキュウアユ', 'Plecoglossus altivelis ryukyuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アリアケシラウオ', 'Salanx ariakensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アリアケヒメシラウオ', 'Neosalanx reganius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ベニザケ（ヒメマス）', 'Oncorhynchus nerka');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'タウナギ属の１種（琉球列島）', 'Monopterus sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ハリヨ', 'Gasterosteus microcephalus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ムサシトミヨ', 'Pungitius sp. 1');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'トミヨ属雄物型', 'Pungitius sp. 2');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ホシイッセンヨウジ', 'Microphis argulus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'タニヨウジ', 'Microphis retzii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヒメテングヨウジ', 'Microphis jagorii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'カワボラ', 'Cestraeus plicatilis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アゴヒゲオコゼ', 'Tetraroge barbata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヒゲソリオコゼ', 'Tetraroge niger');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'カガミテンジクダイ', 'Apogon hyalosoma');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ウラウチフエダイ', 'Lutjanus goldiei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アオギス', 'Sillago parvisquamis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'テッポウウオ', 'Toxotes jaculatorix');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヨコシマイサキ', 'Mesopristes cancellatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ニセシマイサキ', 'Mesopristes argenteus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'シミズシマイサキ', 'Mesopristes iravi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ウラウチヘビギンポ', 'Enneapterygius cheni');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヒルギギンポ', 'Omox biporos');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'カワギンポ', 'Omobranchus ferox');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ツバサハゼ', 'Rhyacichthys aspro');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヤエヤマノコギリハゼ', 'Butis amboinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'トカゲハゼ', 'Scartelaos histophorus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヨロイボウズハゼ', 'Lentipes armatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'カエルハゼ', 'Sicyopus leprurus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アカボウズハゼ', 'Sicyopus zosterophorum');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ハヤセボウズハゼ', 'Stiphodon imperiorientis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'コンテリボウズハゼ', 'Stiphodon atropurpureus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ドウクツミミズハゼ', 'Luciogobius albus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ミスジハゼ', 'Callogobius sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ウラウチイソハゼ', 'Eviota ocellifer');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'シマサルハゼ', 'Oxyurichthys sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヒメトサカハゼ', 'Cristatogobius aurimaculatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'クロトサカハゼ', 'Cristatogobius nonatoae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'イサザ', 'Gymnogobius isaza');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ジュズカケハゼ鳥海山周辺固有種', 'Gymnogobius sp. "Chokai-endemic species"');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ジュズカケハゼ富山固有種', 'Gymnogobius sp. "Toyama-endemic species"');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アゴヒゲハゼ', 'Glossogobius bicirrhosus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'コンジキハゼ', 'Glossogobius aureus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'カワクモハゼ', 'Bathygobius sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'アオバラヨシノボリ', 'Rhinogobius sp. BB');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'コマチハゼ', 'Parioglossus taeniatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'ヒメサツキハゼ', 'Parioglossus interruptus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠA類（CR)', '汽水・淡水魚類', 'タイワンキンギョ', 'Macropodus opercularis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ニホンウナギ', 'Anguilla japonica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ドロクイ', 'Nematalosa japonica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'エツ', 'Coilia nasus ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ゲンゴロウブナ', 'Carassius cuvieri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ニゴロブナ', 'Carassius auratus grandoculis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'タナゴ', 'Acheilognathus melanogaster');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'シロヒレタビラ', 'Acheilognathus tabira tabira');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'アカヒレタビラ', 'Acheilognathus tabira erythropterus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'キタノアカヒレタビラ', 'Acheilognathus tabira tohokuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'カゼトゲタナゴ', 'Rhodeus atremius atremius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'カワバタモロコ', 'Hemigrammocypris rasborella');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ウケクチウグイ', 'Tribolodon nakamurai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ヨドゼゼラ', 'Biwia yodoensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ツチフキ', 'Abbottina rivularis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'イシドジョウ', 'Cobitis takatsuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ヒナイシドジョウ', 'Cobitis shikokuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'オオガタスジシマドジョウ', 'Cobitis magnostriata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'トウカイコガタスジシマドジョウ', 'Cobitis minamorii tokaiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'サンインコガタスジシマドジョウ', 'Cobitis minamorii saninensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ビワコガタスジシマドジョウ（ヨドコガタスジシマドジョウを含む）', 'Cobitis minamorii oumiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'オンガスジシマドジョウ', 'Cobitis striata fuchigamii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'アリアケスジシマドジョウ', 'Cobitis kaibarai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'オオヨドシマドジョウ', 'Cobitis sp. Oyodo form');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'エゾホトケドジョウ', 'Lefua nikkonis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ホトケドジョウ', 'Lefua echigonia');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ナガレホトケドジョウ', 'Lefua sp. 1');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ホトケドジョウ属の１種（東海集団）', 'Lefua sp. 2');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ネコギギ', 'Pseudobagrus ichikawai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'イトウ', 'Hucho perryi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'アミメカワヨウジ', 'Hippichthys heptagonus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ナガレフウライボラ', 'Crenimugil heterocheilos');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ヤマノカミ', 'Trachidermus fasciatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'カジカ小卵型', 'Cottus reinii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'カジカ中卵型', 'Cottus sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'アカメ', 'Lates japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'オヤニラミ', 'Coreoperca kawamebari');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'アトクギス', 'Sillago macrolepis ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'トゲナガユゴイ', 'Kuhlia munda');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ジャノメハゼ', 'Bostrychus sinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'タナゴモドキ', 'Hypseleotris cyprinoides');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'タメトモハゼ', 'Ophieleotris sp. 1');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ゴシキタメトモハゼ', 'Ophieleotris sp. 2');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ムツゴロウ', 'Boleophthalmus pectinirostris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'チワラスボ', 'Taenioides cirratus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'トサカハゼ', 'Cristatogobius lophius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'キセルハゼ', 'Gymnogobius cylindricus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'クボハゼ', 'Gymnogobius scrobiculatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ジュズカケハゼ関東固有種', 'Gymnogobius sp. "Kanto-endemic species"');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'シマエソハゼ', 'Schismatogobius ampluvinculus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'エソハゼ', 'Schismatogobius roxasi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'ホホグロハゼ', 'Mugilogobius parvus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'オガサワラヨシノボリ', 'Rhinogobius ogasawaraensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'キバラヨシノボリ', 'Rhinogobius sp. YB');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧ⅠB類（EN)', '汽水・淡水魚類', 'コビトハゼ', 'Parioglossus rainfordi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'スナヤツメ北方種', 'Lethenteron sp. 1');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'スナヤツメ南方種', 'Lethenteron sp. 2');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'カワヤツメ', 'Lethenteron camtschaticum');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'キンブナ', 'Carassius auratus subsp. 2');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ハス', 'Opsariichthys uncirostris uncirostris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ゼゼラ', 'Biwia zezera');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'デメモロコ', 'Squalidus japonicus japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'スゴモロコ', 'Squalidus chankaensis biwae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'アジメドジョウ', 'Niwaella delicata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'トサシマドジョウ', 'Cobitis sp. BIWAE type D');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'チュウガタスジシマドジョウ', 'Cobitis striata striata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ヤマトシマドジョウ', 'Cobitis matsubarae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ギバチ', 'Pseudobagrus tokiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'アリアケギバチ', 'Pseudobagrus aurantiacus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'アカザ', 'Liobagrus reini');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'オショロコマ', 'Salvelinus malma krascheninnikovi');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ミヤベイワナ', 'Salvelinus malma miyabei');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ゴギ', 'Salvelinus leucomaenis imbrius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'エゾトミヨ', 'Pungitius tymensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'メダカ北日本集団', 'Oryzias sakaizumii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'メダカ南日本集団', 'Oryzias latipes');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'カマキリ（アユカケ）', 'Cottus kazika');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ナンヨウチヌ', 'Acanthopagrus pacificus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'イシドンコ', 'Odontobutis hikimius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ホシマダラハゼ', 'Ophiocara porocephala');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'タビラクチ', 'Apocryptodon punctatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'アサガラハゼ', 'Brachyamblyopus anotus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ワラスボ', 'Odontamblyopus lacepedii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ヒゲワラスボ', 'Taenioides limicola');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ルリボウズハゼ', 'Sicyopterus lagocephalus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'シロウオ', 'Leucopsarion petersii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ミナミヒメミミズハゼ', 'Luciogobius ryukyuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'エドハゼ', 'Gymnogobius macrognathos');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'チクゼンハゼ', 'Gymnogobius uchidai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'シンジコハゼ', 'Gymnogobius taranetzi ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ハゼクチ', 'Acanthogobius hasta');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ミナミアシシロハゼ', 'Acanthogobius insularis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'マサゴハゼ', 'Pseudogobius masago');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ムジナハゼ', 'Mugilogobius sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'キララハゼ', 'Acentrogobius viridipunctatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'マングローブゴマハゼ', 'Pandaka lidwilli');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ゴマハゼ', 'Pandaka sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ギンポハゼ', 'Parkraemeria ornata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅危惧Ⅱ類（VU)', '汽水・淡水魚類', 'ボルネオハゼ', 'Parioglossus palustris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'シベリアヤツメ', 'Lethenteron kessleri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ヤリタナゴ', 'Tanakia lanceolata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'アブラボテ', 'Tanakia limbata');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ヤチウグイ', 'Phoxinus percnurus sachalinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'カワヒガイ', 'Sarcocheilichthys variegatus variegatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'イワトコナマズ', 'Silurus lithophilus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'イシカリワカサギ', 'Hypomesus olidus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'サクラマス（ヤマメ）', 'Oncorhynchus masou masou');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'サツキマス（アマゴ）', 'Oncorhynchus masou ishikawae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ビワマス', 'Oncorhynchus masou subsp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'トミヨ属汽水型', 'Pungitius sp. 3');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'コモチサヨリ', 'Zenarchopterus dunckeri');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'クルメサヨリ', 'Hyporhamphus intermedius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'カジカ大卵型', 'Cottus pollux');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'カワアナゴ科の１種', 'Bunaka gyrinoides');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'トビハゼ', 'Periophthalmus modestus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'イドミミズハゼ', 'Luciogobius pallidus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ユウスイミミズハゼ', 'Luciogobius fonticola');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ナガレミミズハゼ', 'Luciogobius fluvialis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ヒモハゼ', 'Eutaeniichthys gilli');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ジュズカケハゼ広域分布種', 'Gymnogobius sp. "Widely-distributed species"');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'スダレウロハゼ', 'Glossogobius circumspectus ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ワカケサラサハゼ', 'Amblygobius linki');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ニセシラヌイハゼ', 'Silhouettea sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'シラヌイハゼ', 'Silhouettea dotui ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'カブキハゼ', 'Calamiana mindora');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ホクロハゼ', 'Acentrogobius caninus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ニセツムギハゼ', 'Acentrogobius audax');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ホホグロスジハゼ', 'Acentrogobius suluensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'トウカイヨシノボリ', 'Rhinogobius sp. TO');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'シマヒレヨシノボリ', 'Rhinogobius sp. BF ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'シロチチブ', 'Tridentiger nudicervicus ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ショウキハゼ', 'Tridentiger barbatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('準絶滅危惧（NT)', '汽水・淡水魚類', 'ナミノコハゼ', 'Gobitrichinotus radiocularis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ニューギニアウナギ', 'Anguilla  bicolor pacifica');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ナガブナ', 'Carassius auratus subsp. 1');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ヤマナカハヤ', 'Phoxinus lagowskii yamamotis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ドジョウ', 'Misgurnus anguillicaudatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ニッコウイワナ', 'Salvelinus leucomaenis pluvius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'アンピンボラ', 'Chelon subviridis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'オニボラ', 'Ellochelon vaigiensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'カマヒレボラ', 'Moolgarda pedaraki');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'モンナシボラ', 'Moolgarda engeli');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ネッタイイソイワシ', 'Atherinomorus duodecimalis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ミナミギンイソイワシ', 'Hypoatherina temminckii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ナンヨウタカサゴイシモチ', 'Ambassis interrupta');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ハナダカタカサゴイシモチ', 'Ambassis macracanthus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'シラヌイハタ', 'Epinephelus bontoides');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ワキイシモチ', 'Apogon lateralis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ヒルギヌメリテンジクダイ', 'Pseudamia amblyuroptera');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ダイダイコショウダイ', 'Plectorhinchus albovittatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ゴマクモギンポ', 'Omobranchus elongatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ナリタイトヒキヌメリ', 'Pseudocalliurichthys ikedai');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'エリトゲハゼ', 'Belobranchus belobranchus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ヒノコロモボウズハゼ', 'Sicyopus cebuensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'カキイロヒメボウズハゼ', 'Stiphodon surrufus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ネムリミミズハゼ', 'Luciogobius dormitoris');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ドウケハゼ', 'Stenogobius ophthalmoporus ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ヘビハゼ', 'Gymnogobius mororanus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'フタゴハゼ', 'Glossogobius sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'コクチスナゴハゼ', 'Pseudogobius sp.');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'タスキヒナハゼ', 'Redigobius balteatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'フタホシハゼ', 'Mugilogobius fusca');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'ビワヨシノボリ', 'Rhinogobius sp. BW');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'トンガスナハゼ', 'Kraemeria tongaensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'マイコハゼ', 'Parioglossus lineatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('情報不足（DD)', '汽水・淡水魚類', 'クジャクハゼ', 'Parioglossus caeruleolineatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '栃木県のミツバヤツメ', 'Entosphenus tridentatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '本州の太平洋側湖沼系群のニシン', 'Clupea pallasii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '琵琶湖のコイ在来型', 'Cyprinus carpio');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '本州日本海側のマルタ', 'Tribolodon brandtii');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '東北地方のエゾウグイ', 'Tribolodon sachalinensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '襟裳岬以西のシシャモ', 'Spirinchus lanceolatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '紀伊半島のヤマトイワナ（キリクチ）', 'Salvelinus leucomaenis japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '福島県以南の陸封のイトヨ太平洋型', 'Gasterosteus aculeatus aculeatus ');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '本州のイトヨ日本海型', 'Gasterosteus aculeatus aculeatus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '本州のトミヨ属淡水型', 'Pungitius pungitius');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '東北・北陸地方のカンキョウカジカ', 'Cottus hangiongensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '東北地方のハナカジカ', 'Cottus nozawae');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '有明海のスズキ', 'Lateolabrax japonicus');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '北海道南部・東北地方のスミウキゴリ', 'Gymnogobius petschiliensis');
insert into red_data(category, taxon, japanese_name, scientific_name) values('絶滅のおそれのある地域個体群（LP）', '汽水・淡水魚類', '沖縄島のクサフグ', 'Takifugu niphobles');
